// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace WebAPI.Migrations
{
    [DbContext(typeof(TestoviContext))]
    [Migration("20220113005625_V6")]
    partial class V6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Pitanje", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("isArchived")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("Pitanje");
                });

            modelBuilder.Entity("Models.Set", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Set");
                });

            modelBuilder.Entity("Models.SetPitanja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PitanjeID")
                        .HasColumnType("int");

                    b.Property<int?>("SetID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PitanjeID");

                    b.HasIndex("SetID");

                    b.ToTable("SetPitanja");
                });

            modelBuilder.Entity("Models.SetSpojnice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SetID")
                        .HasColumnType("int");

                    b.Property<int?>("SpojnicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SetID");

                    b.HasIndex("SpojnicaID");

                    b.ToTable("SetSpojnice");
                });

            modelBuilder.Entity("Models.SetTagovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SetID")
                        .HasColumnType("int");

                    b.Property<int?>("TagID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SetID");

                    b.HasIndex("TagID");

                    b.ToTable("SetTagovi");
                });

            modelBuilder.Entity("Models.Spojnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Highlighted")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfGames")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("ID");

                    b.ToTable("Spojnica");
                });

            modelBuilder.Entity("Models.SpojnicePitanja", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PitanjeID")
                        .HasColumnType("int");

                    b.Property<int?>("SpojnicaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PitanjeID");

                    b.HasIndex("SpojnicaID");

                    b.ToTable("SpojnicePitanja");
                });

            modelBuilder.Entity("Models.SpojniceTagovi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("SpojnicaID")
                        .HasColumnType("int");

                    b.Property<int?>("TagID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SpojnicaID");

                    b.HasIndex("TagID");

                    b.ToTable("SpojniceTagovi");
                });

            modelBuilder.Entity("Models.Tag", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("Models.SetPitanja", b =>
                {
                    b.HasOne("Models.Pitanje", "Pitanje")
                        .WithMany()
                        .HasForeignKey("PitanjeID");

                    b.HasOne("Models.Set", "Set")
                        .WithMany("SetPitanja")
                        .HasForeignKey("SetID");

                    b.Navigation("Pitanje");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Models.SetSpojnice", b =>
                {
                    b.HasOne("Models.Set", "Set")
                        .WithMany("SetSpojnice")
                        .HasForeignKey("SetID");

                    b.HasOne("Models.Spojnica", "Spojnica")
                        .WithMany()
                        .HasForeignKey("SpojnicaID");

                    b.Navigation("Set");

                    b.Navigation("Spojnica");
                });

            modelBuilder.Entity("Models.SetTagovi", b =>
                {
                    b.HasOne("Models.Set", "Set")
                        .WithMany("SetTagovi")
                        .HasForeignKey("SetID");

                    b.HasOne("Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagID");

                    b.Navigation("Set");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Models.SpojnicePitanja", b =>
                {
                    b.HasOne("Models.Pitanje", "Pitanje")
                        .WithMany()
                        .HasForeignKey("PitanjeID");

                    b.HasOne("Models.Spojnica", "Spojnica")
                        .WithMany("Pitanja")
                        .HasForeignKey("SpojnicaID");

                    b.Navigation("Pitanje");

                    b.Navigation("Spojnica");
                });

            modelBuilder.Entity("Models.SpojniceTagovi", b =>
                {
                    b.HasOne("Models.Spojnica", "Spojnica")
                        .WithMany("Tagovi")
                        .HasForeignKey("SpojnicaID");

                    b.HasOne("Models.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagID");

                    b.Navigation("Spojnica");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Models.Set", b =>
                {
                    b.Navigation("SetPitanja");

                    b.Navigation("SetSpojnice");

                    b.Navigation("SetTagovi");
                });

            modelBuilder.Entity("Models.Spojnica", b =>
                {
                    b.Navigation("Pitanja");

                    b.Navigation("Tagovi");
                });
#pragma warning restore 612, 618
        }
    }
}
